# Generated by Django 5.1.5 on 2025-01-20 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url_output', models.URLField(unique=True)),
            ],
        ),
    ]
