# Generated by Django 5.1.5 on 2025-01-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='url_output',
            field=models.URLField(blank=True, null=True),
        ),
    ]
