# Generated by Django 5.1.5 on 2025-01-19 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
